[no ci] Updated Dockerfile & workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -90,21 +90,65 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Build layer
+        env:
+          DUCKDB_VERSION: '0.8.0'
         run: |
           # Create release folder
           mkdir -p $PWD/release
 
           # Run build
-          docker build -t duckdb-lambda .
+          docker build --build-arg DUCKDB_VERSION=$DUCKDB_VERSION -t duckdb-lambda .
 
           # Copy release from image
-          docker run -v $PWD/release:/opt/mount --rm --entrypoint /bin/bash duckdb-lambda -c "cp /tmp/release/duckdb-layer.zip /opt/mount/"          
+          docker run -v $PWD/release:/opt/mount --rm --entrypoint /bin/bash duckdb-lambda -c "cp /tmp/release/duckdb-layer.zip /opt/mount/"
 
       - name: Upload DuckDB Node build artifact
         uses: actions/upload-artifact@v3
         with:
           name: duckdb-node-zip
           path: release/duckdb-layer.zip
+
+  publish_npm_package:
+    name: Publish duckdb-lambda npm publish_npm_package
+    runs-on: ubuntu-latest
+    needs: [build_duckdb_node]
+
+    steps:
+      - uses: actions/setup-node@v3
+        with:
+          node-version: '16.x'
+          registry-url: 'https://registry.npmjs.org'
+
+      - uses: actions/download-artifact@v3
+        with:
+          name: duckdb-node-zip
+
+      - name: Check for changes and eventually publish new package version
+        env:
+          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+          DUCKDB_VERSION: '0.8.0'
+        run: |
+          # Create layer folder
+          mkdir -p $PWD/layer
+
+          # Unzip to layer folder
+          unzip -d layer/ $PWD/duckdb-layer.zip
+
+          cd $PWD/layer/nodejs/node_modules/duckdb
+
+          # Set package version to DuckDB version (make sure it doesn't fail if the same version exists locally)
+          npm version $DUCKDB_VERSION || true
+
+          # Check the lastest published package version
+          CURRENT_PUBLISHED_PACKAGE_VERSION="${$(npm view duckdb-lambda version 2>/dev/null):-not_published}"
+          # Check local package version
+          CURRENT_LOCAL_PACKAGE_VERSION=$(node -p "require('./package.json').version")
+
+          # Check if package shall be published
+          if [[ "$CURRENT_PUBLISHED_PACKAGE_VERSION" = "not_published" || "$CURRENT_LOCAL_PACKAGE_VERSION" != "$CURRENT_PUBLISHED_PACKAGE_VERSION" ]]; then
+            # Publish to npm
+            npm publish
+          fi
 
   publish_layer_without_extensions:
     name: Publish layer without extensions
